name: Build debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find and Make Gradle wrapper executable
        run: |
          GRADLEW_PATH=$(find . -name gradlew -type f)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "::error::gradlew file not found in repository!"
            exit 1
          fi
          chmod +x "$GRADLEW_PATH"
          echo "FOUND_DIR=$(dirname "$GRADLEW_PATH")" >> $GITHUB_ENV

      - name: Build Debug APK
        run: |
          cd "$FOUND_DIR"
          ./gradlew assembleDebug

      - name: Find and Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wl-orders-debug-apk
          path: '**/app-debug.apk'
